// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzEvinPjWToyskPtVyXlTvhh7GTtwwBdY',
    appId: '1:420747689892:android:22c0a70ebff7dea58a0b31',
    messagingSenderId: '420747689892',
    projectId: 'mike-cab',
    databaseURL: 'https://mike-cab-default-rtdb.firebaseio.com',
    storageBucket: 'mike-cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Lxk_t_dX0W7dkvLW1aSp0tyynBGqhFI',
    appId: '1:420747689892:ios:855f1af7856d3d6e8a0b31',
    messagingSenderId: '420747689892',
    projectId: 'mike-cab',
    databaseURL: 'https://mike-cab-default-rtdb.firebaseio.com',
    storageBucket: 'mike-cab.appspot.com',
    iosClientId: '420747689892-usp8jgquq0om2ue589ecb11r8hee5gdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mikeCab',
  );
}
